# Generated by Django 4.2.5 on 2023-09-10 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_expense_entry_wallet_created_alter_wallet_budget_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='total_expense',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='wallet',
            name='total_income',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
