# Generated by Django 4.2.5 on 2023-09-11 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_wallet_last_entry'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.ImageField(default='blank-pfp.png', upload_to='category-icons'),
        ),
    ]
