# Generated by Django 4.2.5 on 2023-10-17 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_category_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='description',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='income',
            name='description',
            field=models.TextField(blank=True, max_length=100),
        ),
    ]
