# Generated by Django 4.2.5 on 2023-10-19 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_entrytype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='type_x',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.entrytype'),
        ),
    ]
