# Generated by Django 4.2.5 on 2023-09-09 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_accounts_account'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
    ]
